import { UniversalComponent, ComponentFilePayload, EcosystemFlavor } from '../schema';
import { generateOuterLayerFiles } from '../templates/outer-layer';
import { CORE_COMPONENT_DEPENDENCIES } from '../templates/common-deps';

export const borderBeamComponent: UniversalComponent = {
	id: 'border-beam',
	name: 'Border Beam',
	slug: 'border-beam',
	category: 'cards',
	description: 'Zero-runtime CSS perimeter laser trace with hardware mask clipping and sub-pixel compositing.',
	version: '1.0.0',
	props: [
		{
			name: 'size',
			label: 'Beam Length (px)',
			type: 'number',
			defaultValue: 200,
			min: 50,
			max: 200,
			step: 10,
			description: 'Length/size of the perimeter laser trace.',
		},
		{
			name: 'duration',
			label: 'Duration (s)',
			type: 'number',
			defaultValue: 8,
			min: 2,
			max: 30,
			step: 1,
			description: 'Loop duration for one full border sweep.',
		},
		{
			name: 'borderWidth',
			label: 'Border Width (px)',
			type: 'number',
			defaultValue: 2,
			min: 1,
			max: 8,
			step: 0.5,
			description: 'Perimeter border stroke width.',
		},
		{
			name: 'colorFrom',
			label: 'Color From',
			type: 'color',
			defaultValue: '#ffaa40',
			description: 'Starting gradient color.',
		},
		{
			name: 'colorTo',
			label: 'Color To',
			type: 'color',
			defaultValue: '#9c40ff',
			description: 'Ending gradient color.',
		},
		{
			name: 'doubleBeam',
			label: 'Double Beam',
			type: 'boolean',
			defaultValue: false,
			description: 'Render a secondary beam located on the opposite side of the perimeter, orbiting in the same direction (180° phase offset).',
		},
		{
			name: 'endOpacity',
			label: 'End Opacity',
			type: 'number',
			defaultValue: 0,
			min: 0,
			max: 1,
			step: 0.05,
			description: 'Opacity of the beam tail at its trailing edge (0 for pure transparent).',
		},
		{
			name: 'opacity',
			label: 'Opacity',
			type: 'number',
			defaultValue: 1,
			min: 0,
			max: 1,
			step: 0.05,
			description: 'Overall opacity of the border beam trace.',
		},
		{
			name: 'blur',
			label: 'Glow Blur (px)',
			type: 'number',
			defaultValue: 0,
			min: 0,
			max: 12,
			step: 1,
			description: 'Specular diffuse blur applied to the perimeter laser trace.',
		},
		{
			name: 'borderRadius',
			label: 'Corner Radius (px)',
			type: 'number',
			defaultValue: 16,
			min: 0,
			max: 48,
			step: 2,
			description: 'Corner radius of the perimeter path matching card borders.',
		},
	],
	defaultProps: {
		size: 200,
		duration: 8,
		borderWidth: 2,
		colorFrom: '#ffaa40',
		colorTo: '#9c40ff',
		doubleBeam: false,
		endOpacity: 0,
		opacity: 1,
		blur: 0,
		borderRadius: 16,
	},
	dependencies: CORE_COMPONENT_DEPENDENCIES,
	generateCode: (flavor: EcosystemFlavor, props: Record<string, unknown>, options?: { eject?: boolean }): ComponentFilePayload[] => {
		return generateOuterLayerFiles(
			{
				id: 'border-beam',
				name: 'Border Beam',
				slug: 'border-beam',
				category: 'cards',
				pascalName: 'BorderBeam',
				snakeName: 'border_beam',
				description: 'Zero-runtime CSS perimeter laser trace with hardware mask clipping.',
				defaultTailwindClass: 'pointer-events-none absolute inset-0 rounded-[inherit]',
			},
			flavor,
			props,
			options
		);
	},
};
