import { UniversalComponent, ComponentFilePayload, EcosystemFlavor } from '../schema';
import { generateOuterLayerFiles } from '../templates/outer-layer';
import { CORE_COMPONENT_DEPENDENCIES } from '../templates/common-deps';

export const cssMasonryComponent: UniversalComponent = {
	id: 'css-masonry',
	name: 'CSS Masonry',
	slug: 'css-masonry',
	category: 'layouts',
	description: 'Pure CSS multi-column responsive masonry layout with zero external JavaScript runtime overhead.',
	version: '1.0.0',
	props: [
		{
			name: 'columns',
			label: 'Mobile Columns (<640px)',
			type: 'number',
			defaultValue: 1,
			min: 1,
			max: 8,
			step: 1,
			description: 'Base column count on mobile viewports (<640px).',
		},
		{
			name: 'columnsSm',
			label: 'Tablet Columns (640-1024px)',
			type: 'number',
			defaultValue: 2,
			min: 1,
			max: 4,
			step: 1,
			description: 'Number of columns on tablet viewports (≥640px).',
		},
		{
			name: 'columnsMd',
			label: 'Medium Tablet Columns',
			type: 'number',
			defaultValue: 2,
			min: 1,
			max: 6,
			step: 1,
			description: 'Number of columns on medium tablet viewports.',
		},
		{
			name: 'columnsLg',
			label: 'Desktop Columns (1024-1280px)',
			type: 'number',
			defaultValue: 3,
			min: 1,
			max: 8,
			step: 1,
			description: 'Number of columns on desktop viewports.',
		},
		{
			name: 'columnsXl',
			label: 'Ultra-wide Columns (≥1280px)',
			type: 'number',
			defaultValue: 4,
			min: 1,
			max: 10,
			step: 1,
			description: 'Number of columns on large screens (≥1280px).',
		},
		{
			name: 'gap',
			label: 'Gap (px)',
			type: 'number',
			defaultValue: 16,
			min: 4,
			max: 64,
			step: 4,
			description: 'Spacing between masonry columns and item margins.',
		},
		{
			name: 'columnFill',
			label: 'Column Fill',
			type: 'select',
			defaultValue: 'balance',
			options: [
				{ label: 'Balance (Balanced Heights)', value: 'balance' },
				{ label: 'Auto (Sequential Waterfall)', value: 'auto' },
			],
			description: 'Controls whether column heights are balanced or filled sequentially.',
		},
		{
			name: 'height',
			label: 'Container Height (px)',
			type: 'number',
			defaultValue: 0,
			min: 0,
			max: 1200,
			step: 20,
			description: 'Explicit container height for sequential waterfall (0 for auto balance).',
		},
	],
	defaultProps: {
		columns: 1,
		columnsSm: 2,
		columnsMd: 2,
		columnsLg: 3,
		columnsXl: 4,
		gap: 16,
		columnFill: 'balance',
		height: 0,
	},
	dependencies: CORE_COMPONENT_DEPENDENCIES,
	generateCode: (flavor: EcosystemFlavor, props: Record<string, unknown>, options?: { eject?: boolean }): ComponentFilePayload[] => {
		return generateOuterLayerFiles(
			{
				id: 'css-masonry',
				name: 'CSS Masonry',
				slug: 'css-masonry',
				category: 'layouts',
				pascalName: 'CssMasonry',
				snakeName: 'css_masonry',
				description: 'Pure CSS multi-column responsive masonry layout.',
				defaultTailwindClass: 'columns-1 sm:columns-2 md:columns-3 gap-4 [column-fill:_balance] w-full space-y-4',
				compoundParts: [
					{
						name: 'CssMasonryItem',
						primitiveExport: 'CssMasonryItem',
						defaultClass: '',
					},
				],
			},
			flavor,
			props,
			options
		);
	},
};
