import { UniversalComponent, ComponentFilePayload, EcosystemFlavor } from '../schema';
import { generateOuterLayerFiles } from '../templates/outer-layer';
import { CORE_COMPONENT_DEPENDENCIES } from '../templates/common-deps';

export const spotlightCardComponent: UniversalComponent = {
	id: 'spotlight-card',
	name: 'Spotlight Card',
	slug: 'spotlight-card',
	category: 'cards',
	description: 'Dynamic 2D spatial coordinate tracking with sub-pixel radial border illumination mask and smooth exponential smoothing.',
	version: '1.0.0',
	props: [
		{
			name: 'radius',
			label: 'Spotlight Radius (px)',
			type: 'number',
			defaultValue: 350,
			min: 150,
			max: 800,
			step: 25,
			description: 'Radius of the radial spotlight illumination in pixels.',
		},
		{
			name: 'color',
			label: 'Spotlight Color',
			type: 'color',
			defaultValue: '#6366f1',
			description: 'Background radial sheen color (CSS color string or hex).',
		},
		{
			name: 'borderColor',
			label: 'Border Glow Color',
			type: 'color',
			defaultValue: '#818cf8',
			description: 'Color of the illuminated border edge specular mask.',
		},
		{
			name: 'opacity',
			label: 'Glow Opacity',
			type: 'number',
			defaultValue: 0.85,
			min: 0.0,
			max: 1.0,
			step: 0.05,
			description: 'Opacity of the spotlight when cursor is active over the card.',
		},
		{
			name: 'spread',
			label: 'Falloff Spread (%)',
			type: 'number',
			defaultValue: 60,
			min: 20,
			max: 100,
			step: 5,
			description: 'Radial gradient falloff softness percentage.',
		},
		{
			name: 'mode',
			label: 'Spotlight Mode',
			type: 'select',
			defaultValue: 'both',
			options: [
				{ label: 'Both (Border & Sheen)', value: 'both' },
				{ label: 'Border Only', value: 'border' },
				{ label: 'Background Sheen Only', value: 'background' },
			],
			description: 'Select whether to illuminate the border mask, background sheen, or both.',
		},
		{
			name: 'smoothing',
			label: 'Inertial Smoothing',
			type: 'number',
			defaultValue: 0.2,
			min: 0.05,
			max: 1.0,
			step: 0.05,
			description: 'Kinetic exponential smoothing response rate (1.0 = instant, 0.1 = silky inertia).',
		},
		{
			name: 'disabled',
			label: 'Disable Tracking',
			type: 'boolean',
			defaultValue: false,
			description: 'Programmatically disable pointer tracking and spotlight illumination.',
		},
	],
	defaultProps: {
		radius: 350,
		color: '#6366f1',
		borderColor: '#818cf8',
		opacity: 0.85,
		spread: 60,
		mode: 'both',
		smoothing: 0.2,
		disabled: false,
	},
	dependencies: CORE_COMPONENT_DEPENDENCIES,
	generateCode: (flavor: EcosystemFlavor, props: Record<string, unknown>, options?: { eject?: boolean }): ComponentFilePayload[] => {
		return generateOuterLayerFiles(
			{
				id: 'spotlight-card',
				name: 'Spotlight Card',
				slug: 'spotlight-card',
				category: 'cards',
				pascalName: 'SpotlightCard',
				snakeName: 'spotlight_card',
				description: 'Dynamic 2D spatial coordinate tracking with sub-pixel radial border illumination mask and smooth exponential smoothing.',
				defaultTailwindClass: 'relative overflow-hidden rounded-2xl border border-border bg-card p-6 shadow-sm transition-shadow hover:shadow-md will-change-transform',
			},
			flavor,
			props,
			options
		);
	},
};
