import { EcosystemFlavor, REGISTRY_BASE_URL } from '../constants';
import canonicalRegistry from '../registry/canonical.json';

export interface ComponentFilePayload {
	filename: string;
	language: string;
	code: string;
	description?: string;
}

export interface RegistryComponentResponse {
	id: string;
	name: string;
	slug: string;
	category: string;
	description: string;
	version: string;
	files: ComponentFilePayload[];
}

export async function fetchComponentFromRegistry(slug: string, flavor: EcosystemFlavor, baseUrl: string = REGISTRY_BASE_URL): Promise<ComponentFilePayload[]> {
	try {
		const url = `${baseUrl}/${slug}?flavor=${flavor}`;
		const res = await fetch(url, {
			headers: {
				'User-Agent': 'exhuma-cli/0.1.1',
			},
		});

		if (res.ok) {
			const data = (await res.json()) as RegistryComponentResponse;
			if (data.files && Array.isArray(data.files)) {
				return data.files;
			}
		}
	} catch {
		// Network fetch failed, try embedded canonical fallback
	}

	// Fallback to embedded canonical registry (100% offline & out-of-the-box safe)
	return getFallbackFiles(slug, flavor);
}

function getFallbackFiles(slug: string, flavor: EcosystemFlavor): ComponentFilePayload[] {
	const registry = canonicalRegistry as Record<string, Record<EcosystemFlavor, ComponentFilePayload[]>>;
	const compFlavors = registry[slug];
	if (compFlavors && compFlavors[flavor]) {
		return compFlavors[flavor];
	}

	return [
		{
			filename: `${slug}.tsx`,
			language: 'tsx',
			description: `Exhuma ${slug} component.`,
			code: `// Exhuma ${slug} (${flavor})\n// Generated by exhuma CLI\n`,
		},
	];
}
