import { EcosystemFlavor, REGISTRY_BASE_URL } from '../constants';
import canonicalRegistry from '../registry/canonical.json';

export interface ComponentFilePayload {
	filename: string;
	language: string;
	code: string;
	description?: string;
}

export interface RegistryComponentResponse {
	id: string;
	name: string;
	slug: string;
	category: string;
	description: string;
	version: string;
	files: ComponentFilePayload[];
}

export interface FetchRegistryOptions {
	baseUrl?: string;
	eject?: boolean;
}

export async function fetchComponentFromRegistry(
	slug: string,
	flavor: EcosystemFlavor,
	options?: FetchRegistryOptions | string
): Promise<ComponentFilePayload[]> {
	const opts: FetchRegistryOptions = typeof options === 'string' ? { baseUrl: options } : options || {};
	const baseUrl = opts.baseUrl || REGISTRY_BASE_URL;
	const isEjected = opts.eject === true;

	try {
		const url = `${baseUrl}/${slug}?flavor=${flavor}${isEjected ? '&eject=true' : ''}`;
		const res = await fetch(url, {
			headers: {
				'User-Agent': 'exhuma-cli/0.1.1',
			},
		});

		if (res.ok) {
			const data = (await res.json()) as RegistryComponentResponse;
			if (data.files && Array.isArray(data.files)) {
				return data.files;
			}
		}
	} catch {
		// Network fetch failed, try embedded canonical fallback
	}

	// Fallback to embedded canonical registry (100% offline & out-of-the-box safe)
	return getFallbackFiles(slug, flavor, isEjected);
}

function getFallbackFiles(slug: string, flavor: EcosystemFlavor, isEjected: boolean = false): ComponentFilePayload[] {
	const registry = canonicalRegistry as Record<string, Record<EcosystemFlavor, ComponentFilePayload[]>>;
	const key = isEjected ? `${slug}:ejected` : slug;
	const compFlavors = registry[key] || registry[slug];
	if (compFlavors && compFlavors[flavor]) {
		return compFlavors[flavor];
	}

	return [
		{
			filename: `${slug}.tsx`,
			language: 'tsx',
			description: `Exhuma ${slug} component.`,
			code: `// Exhuma ${slug} (${flavor})\n// Generated by exhuma CLI\n`,
		},
	];
}
